<?php

/***********************
 * DRUPAL HOOKS
 ***********************/

/**
 * Implements hook_menu()
 */
function cm2_menu() {
	$items['admin/structure/cm2-redirect'] = array(
		'title' => 'CM2 Settings',
		'description' => 'Set domain values for mobile redirection',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cm2_settings_form'),
		'access arguments' => array('access cm2 settings'),
	);
	$items['redirect/%cm2_menu_tail'] = array(
		'title' => 'Redirect',
		'page callback' => '_cm2_redirect',
		'page arguments' => array(1),
		'access callback' => TRUE,
	);
	
	return $items;
}

/**
 * Implements hook_theme
 */
function cm2_theme($existing, $type, $theme, $path) {
	return array(
		'cm2_link' => array(
	      'variables' => array(),
    	),
    );
}

/**
 * Implements hook_boot()
 */
function cm2_boot() {
  // if cookie is set break out so we don't loop.
  if (isset($_COOKIE['cm2_desktop'])) {
    return;
  }
  // break out if already in mobile
  if ($GLOBALS['base_url'] == "http://".variable_get('cm2_mobile')) {
    return;
  }
  // prepare redirect value
  $simplemobileredirect = FALSE;
  // get the user agent
  $user_agent = $_SERVER['HTTP_USER_AGENT'];
  // using a switch to check for the user agent, smoother than a searies of if's
  switch (TRUE) {
    // find the word ipad in the user agent
    case (preg_match('/ipad/i', $user_agent)):
    // find the word iphone in the user agent
    case (preg_match('/ipod/i', $user_agent) || preg_match('/iphone/i', $user_agent)):
    // we find android in the user agent
    case (preg_match('/android/i', $user_agent)):
    // we find opera mini in the user agent
    case (preg_match('/opera mini/i', $user_agent)):
    // we find blackberry in the user agent
    case (preg_match('/blackberry/i', $user_agent)):
    // we find palm os in the user agent
    case (preg_match('/(pre\/|palm os|palm|hiptop|avantgo|plucker|xiino|blazer|elaine)/i', $user_agent)):
    // we find windows mobile in the user agent - the i at the end makes it case insensitive
    case (preg_match('/(iris|3g_t|windows ce|opera mobi|windows ce; smartphone;|windows ce; iemobile)/i', $user_agent)):
    // check if any of the values listed create a match on the user agent - these are some of the most common terms used in agents to identify them as being mobile devices
    case (preg_match('/(mini 9.5|vx1000|lge |m800|e860|u940|ux840|compal|wireless| mobi|ahong|lg380|lgku|lgu900|lg210|lg47|lg920|lg840|lg370|sam-r|mg50|s55|g83|t66|vx400|mk99|d615|d763|el370|sl900|mp500|samu3|samu4|vx10|xda_|samu5|samu6|samu7|samu9|a615|b832|m881|s920|n210|s700|c-810|_h797|mob-x|sk16d|848b|mowser|s580|r800|471x|v120|rim8|c500foma:|160x|x160|480x|x640|t503|w839|i250|sprint|w398samr810|m5252|c7100|mt126|x225|s5330|s820|htil-g1|fly v71|s302|-x113|novarra|k610i|-three|8325rc|8352rc|sanyo|vx54|c888|nx250|n120|mtk |c5588|s710|t880|c5005|i;458x|p404i|s210|c5100|teleca|s940|c500|s590|foma|samsu|vx8|vx9|a1000|_mms|myx|a700|gu1100|bc831|e300|ems100|me701|me702m-three|sd588|s800|8325rc|ac831|mw200|brew |d88|htc\/|htc_touch|355x|m50|km100|d736|p-9521|telco|sl74|ktouch|m4u\/|me702|8325rc|kddi|phone|lg |sonyericsson|samsung|240x|x320|vx10|nokia|sony cmd|motorola|up.browser|up.link|mmp|symbian|smartphone|midp|wap|vodafone|o2|pocket|kindle|mobile|psp|treo)/i', $user_agent)):
    // is the device showing signs of support for text/vnd.wap.wml or application/vnd.wap.xhtml+xml
    case ((strpos($_SERVER['HTTP_ACCEPT'], 'text/vnd.wap.wml') > 0) || (strpos($_SERVER['HTTP_ACCEPT'], 'application/vnd.wap.xhtml+xml') > 0)):
    // is the device giving us a HTTP_X_WAP_PROFILE or HTTP_PROFILE header - only mobile devices would do this
    case (isset($_SERVER['HTTP_X_WAP_PROFILE']) || isset($_SERVER['HTTP_PROFILE'])):
      $simplemobileredirect = variable_get('cm2_mobile', '');
    break;
  }
  // if redirect (either the value of the mobile or desktop redirect depending on the value of $is_mobile_browser) is TRUE redirect else we return the status of $is_mobile_browser
  if ($simplemobileredirect) {
    // header("Location: http://$simplemobileredirect/{$_GET['q']}", TRUE, 302);
    // redirect to homepage only
    header("Location: http://$simplemobileredirect", TRUE, 302);
    exit;
  }
}

/**********************************
 * PREPROCESSING
 *********************************/
/**
 * Implements MYMODULE_preprocess()
 */
function cm2_preprocess_link(&$vars) {
  if (strstr($vars['path'],"redirect/mobile")) {
    $vars['theme_hook_suggestions'][] = 'cm2_link';
  }
  if (strstr($vars['path'],"redirect/desktop")) {
    $vars['theme_hook_suggestions'][] = 'cm2_link';
  }
}

/***********************
 * MENU CALLBACKS
 ***********************/

/**
 * Callback for:
 * 		cm2-redirect/%cm2_menu_tail
 * 
 * @param $type
 * 		argument in the URL
 * 
 * @return void
 */
function _cm2_redirect($type) {
	$url = FALSE;
	$path = drupal_parse_url($type);
	$newpath = isset($path['query']['destination']) ? str_replace('---','/',"/{$path['query']['destination']}") : '';
	switch ($path['path']) {
		case 'desktop':
			setcookie('cm2_desktop',1,REQUEST_TIME + 31536000,'/',variable_get('cm2_desktop',''));
			$url = variable_get('cm2_desktop','');
			break;
		case 'mobile':
			setcookie('cm2_desktop',0,REQUEST_TIME - 3600,'/',variable_get('cm2_desktop',''));
			$url = variable_get('cm2_mobile','');
			break;
	}
	// actual redirection
	if ($url) {
		// header("Location: http://$url$newpath", TRUE, 302);
		// redirect to homepage only
		header("Location: http://$url", TRUE, 302);
	} else {
		header("Location: {$GLOBALS['base_url']}", TRUE, 302);
	}
	exit;
}
/**
 * Callback for cm2redirect
 */
function _cm2_dummy() {
	return '';
}
/**
 * cm2_menu_tail_to_arg
 */
function cm2_menu_tail_to_arg($arg) {
	if (empty($arg) || $arg == '%') {
		if ($GLOBALS['base_url'] == "http://".variable_get('cm2_desktop')) {
			$arg = "mobile";
		} else {
			$arg = "desktop";
		}
	}
	return $arg."?destination=".str_replace('/', '---', drupal_get_path_alias($_GET['q']));
}
/************************
 * FORMS
 ************************/
/**
 * Settings form
 */
function cm2_settings_form($form_state) {
	$form['cm2_desktop'] = array(
		'#title' => 'Desktop Domain',
		'#type' => 'textfield',
		'#field_prefix' => 'http://',
		'#field_suffix' => '/',
		'#default_value'=>variable_get('cm2_desktop'),
		'#required' => TRUE,
	);
	$form['cm2_mobile'] = array(
		'#title' => 'Mobile Domain',
		'#type' => 'textfield',
		'#field_prefix' => 'http://',
		'#field_suffix' => '/',
		'#default_value'=>variable_get('cm2_mobile'),
		'#required' => TRUE,
	);
	
	return system_settings_form($form);
}

/********************************
 * THEME FUNCTIONS
 ********************************/

/**
 * theme menu_link
 */
function theme_cm2_link($vars) {
  if (strstr($vars['path'],"redirect/mobile")) {
  	$vars['text'] = t('Mobile Version');
  }
  if (strstr($vars['path'],"redirect/desktop")) {
  	$vars['text'] = t('Full Version');
  }
  return theme_link($vars);
}